package com.github.williansmercante.serviconfse.service;

public class TiposNfe {

    public String nfe(Object object) {
        StringBuilder nfe = new StringBuilder();
        nfe.append("");

        nfe.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
        nfe.append("<xs:schema targetNamespace=\"http://www.prefeitura.sp.gov.br/nfe/tipos\"");
        nfe.append("xmlns:tipos=\"http://www.prefeitura.sp.gov.br/nfe/tipos\"");
        nfe.append("xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">");
        nfe.append("<xs:import namespace=\"http://www.w3.org/2000/09/xmldsig#\" schemaLocation=\"xmldsig-core-schema_v02.xsd\" />");
        nfe.append("<!-- Tipos Simples -->");
        nfe.append("<xs:simpleType name=\"tpAliquota\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo utilizado para valor de alíquota</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:decimal\">");
        nfe.append("<xs:totalDigits value=\"5\" />");
        nfe.append("<xs:fractionDigits value=\"4\" />");
        nfe.append("<xs:minInclusive value=\"0\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpAssinatura\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Assinatura digital do RPS emitido.</xs:documentation>");
        nfe.append("<xs:documentation>O RPS deverá ser assinado digitalmente. O contribuinte deverá assinar uma cadeia de caracteres (ASCII) com informações do RPS emitido.</xs:documentation>");
        nfe.append("<xs:documentation>O certificado digital utilizado na assinatura de cancelamento deverá ser o mesmo utilizado na assinatura da mensagem XML. A cadeia de caracteres a ser assinada deverá conter 86 posições com as informações apresentadas a seguir:</xs:documentation>");
        nfe.append("<xs:documentation>Inscrição Municipal (CCM) do Prestador com 8 caracteres. Caso o CCM do Prestador tenha menos de 8 caracteres, o mesmo deverá ser completado com zeros à esquerda.</xs:documentation>");
        nfe.append("<xs:documentation>Série do RPS com 5 posições. Caso a Série do RPS tenha menos de 5 caracteres, o mesmo deverá ser completado com espaços em branco à direita.</xs:documentation>");
        nfe.append("<xs:documentation>Número do RPS com 12 posições. Caso o Número do RPS tenha menos de 12 caracteres, o mesmo deverá ser completado com zeros à esquerda.</xs:documentation>");
        nfe.append("<xs:documentation>Data da emissão do RPS no formato AAAAMMDD.</xs:documentation>");
        nfe.append("<xs:documentation>Tipo de Tributação do RPS com uma posição (sendo T: para Tributação no municipio de São Paulo; F: para Tributação fora do municipio de São Paulo; I: para Isento; J: para ISS Suspenso por Decisão Judicial).</xs:documentation>");
        nfe.append("<xs:documentation>Status do RPS com uma posição (sendo N: Normal, C: Cancelado; E: Extraviado).</xs:documentation>");
        nfe.append("<xs:documentation>ISS Retido com uma posição (sendo S: ISS Retido; N: Nota Fiscal sem ISS Retido).</xs:documentation>");
        nfe.append("<xs:documentation>Valor dos Serviços com 15 posições e sem separador de milhar e decimal.</xs:documentation>");
        nfe.append("<xs:documentation>Valor das Deduções com 15 posições e sem separador de milhar e decimal.</xs:documentation>");
        nfe.append("<xs:documentation>Código do Serviço com 5 posições.</xs:documentation>");
        nfe.append("<xs:documentation>CPF/CNPJ do tomador com 14 posições. Sem formatação (ponto, traço, barra, ....). Completar com zeros à esquerda caso seja necessário. Se o Indicador do CPF/CNPJ for 3 (não-informado), preencher com 14 zeros.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:base64Binary\">");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpAssinaturaCancelamento\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Assinatura digital de cancelamento da NFS-e.</xs:documentation>");
        nfe.append("<xs:documentation>Cada NFS-e a ser cancelada deverá ter sua respectiva assinatura de cancelamento. O contribuinte deverá assinar uma cadeia de caracteres (ASCII) com informações da NFS-e a ser cancelada.</xs:documentation>");
        nfe.append("<xs:documentation>O certificado digital utilizado na assinatura de cancelamento deverá ser o mesmo utilizado na assinatura da mensagem XML. A cadeia de caracteres a ser assinada deverá conter 20 posições com as informações apresentadas a seguir:</xs:documentation>");
        nfe.append("<xs:documentation>Inscrição Municipal (CCM) do Prestador com 8 caracteres. Caso o CCM do Prestador tenha menos de 8 caracteres, o mesmo deverá ser completado com zeros à esquerda.</xs:documentation>");
        nfe.append("<xs:documentation>Número da NFS-e RPS com 12 posições. Caso o Número da NFS-e tenha menos de 12 caracteres, o mesmo deverá ser completado com zeros à esquerda.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:base64Binary\">");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpBairro\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo bairro.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:minLength value=\"0\" />");
        nfe.append("<xs:maxLength value=\"30\" />");
        nfe.append("<xs:whiteSpace value=\"collapse\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpCCIB\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Cadastro de imóveis. Obrigatório para construção civil.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:whiteSpace value=\"preserve\"/>");
        nfe.append("<xs:pattern value=\"[0-9A-Z]{8}\"/>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpCClassTribReg\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Código de classificação Tributária do IBS e da CBS secundário, que informa a tributação original ser utilizada caso os requisitos da suspensão não sejam cumpridos.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:long\">");
        nfe.append("<xs:pattern value=\"[0-9]{6}\"/>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpCClassTribIBSCBS\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Código de classificação Tributária do IBS e da CBS principal.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:long\">");
        nfe.append("<xs:pattern value=\"[0-9]{6}\"/>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpCEP\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo CEP.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:int\">");
        nfe.append("<xs:pattern value=\"[0-9]{7,8}\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpCidade\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo Código do Município segundo tabela IBGE.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:int\">");
        nfe.append("<xs:pattern value=\"[0-9]{7}\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpCNPJ\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo CNPJ.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:pattern value=\"[0-9A-Z]{12}[0-9]{2}\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpCodigoServico\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo código de serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:int\">");
        nfe.append("<xs:pattern value=\"[0-9]{4,5}\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpCodigoEvento\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo código de evento.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:short\">");
        nfe.append("<xs:pattern value=\"[0-9]{3,4}\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpCodigoEndPostal\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Código de endereçamento postal</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:whiteSpace value=\"preserve\"/>");
        nfe.append("<xs:minLength value=\"1\"/>");
        nfe.append("<xs:maxLength value=\"11\"/>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpCodigoNBS\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>");
        nfe.append("Código da lista de Nomenclatura Brasileira de Serviços (NBS)");
        nfe.append("</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:whiteSpace value=\"preserve\"/>");
        nfe.append("<xs:pattern value=\"[0-9]{9}\"/>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpCodigoNCM\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>");
        nfe.append("Código da lista de Nomenclatura Comum do Mercosul (NCM)");
        nfe.append("</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:whiteSpace value=\"preserve\"/>");
        nfe.append("<xs:pattern value=\"[0-9]{8}\"/>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpCodigoPaisISO\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo Código do País segundo tabela ISO.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:whiteSpace value=\"preserve\"/>");
        nfe.append("<xs:pattern value=\"[A-Z]{2}\"/>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpCodigoVerificacao\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo Código de verificação da NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:minLength value=\"8\" />");
        nfe.append("<xs:maxLength value=\"8\" />");
        nfe.append("<xs:whiteSpace value=\"collapse\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpComplementoEndereco\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo complemento do endereço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:minLength value=\"0\" />");
        nfe.append("<xs:maxLength value=\"30\" />");
        nfe.append("<xs:whiteSpace value=\"collapse\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpEnteGov\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo do ente da compra governamental.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:enumeration value=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>União.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"2\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Estados.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"3\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Distrito Federal.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"4\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Municípios.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>		");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpCPF\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo CPF.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:pattern value=\"[0-9]{0}|[0-9]{11}\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpDescricaoEvento\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo descrição do evento.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:minLength value=\"0\" />");
        nfe.append("<xs:maxLength value=\"300\" />");
        nfe.append("<xs:whiteSpace value=\"collapse\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpDiscriminacao\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo Discriminação Serviços.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:minLength value=\"1\" />");
        nfe.append("<xs:maxLength value=\"2000\" />");
        nfe.append("<xs:whiteSpace value=\"collapse\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpEmail\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo E-mail.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:minLength value=\"0\" />");
        nfe.append("<xs:maxLength value=\"75\" />");
        nfe.append("<xs:whiteSpace value=\"collapse\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpEstadoProvinciaRegiao\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Estado, província ou região</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:whiteSpace value=\"preserve\"/>");
        nfe.append("<xs:minLength value=\"1\"/>");
        nfe.append("<xs:maxLength value=\"60\"/>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpExigibilidadeSuspensa\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo emissão com exigibilidade suspensa.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:enumeration value=\"0\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Não.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Sim.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpFonteCargaTributaria\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo utilizado para a fonte da carga tributária.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:minLength value=\"0\" />");
        nfe.append("<xs:maxLength value=\"10\" />");
        nfe.append("<xs:whiteSpace value=\"collapse\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpIndicadorCompraGov\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo do indicador de compra governamental.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:enumeration value=\"0\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Não.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Sim.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpInscricaoEstadual\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo Inscrição Estadual.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:long\">");
        nfe.append("<xs:pattern value=\"[0-9]{1,19}\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpInscricaoMunicipal\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo padrão referente a inscrição municipal.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:long\">");
        nfe.append("<xs:pattern value=\"[0-9]{1,12}\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpLogradouro\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Endereço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:minLength value=\"0\" />");
        nfe.append("<xs:maxLength value=\"50\" />");
        nfe.append("<xs:whiteSpace value=\"collapse\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpModoPrestacaoServico\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo Modo de prestação do serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:enumeration value=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Presencial.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"2\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Não presencial.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpNaoNIF\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo do motivo para não informação do NIF.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:whiteSpace value=\"preserve\"/>");
        nfe.append("<xs:enumeration value=\"0\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>0 - Não informado na nota de origem;</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>1 - Dispensado do NIF;</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"2\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>2 - Não exigência do NIF;</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpNIF\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo NIF (Número de Identificação Fiscal) - fornecido por um órgão de administração tributária no exterior.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:minLength value=\"1\" />");
        nfe.append("<xs:maxLength value=\"40\" />");
        nfe.append("<xs:whiteSpace value=\"preserve\"/>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpNomeCidade\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Nome da Cidade</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:whiteSpace value=\"preserve\"/>");
        nfe.append("<xs:minLength value=\"1\"/>");
        nfe.append("<xs:maxLength value=\"60\"/>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpNumero\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo número.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:long\">");
        nfe.append("<xs:pattern value=\"[0-9]{1,12}\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpNumeroEndereco\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo número do endereço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:minLength value=\"0\" />");
        nfe.append("<xs:maxLength value=\"10\" />");
        nfe.append("<xs:whiteSpace value=\"collapse\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpOnerosidade\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo de indicador de operação onerosa.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:enumeration value=\"0\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Não onerosa.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Onerosa.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpOpcaoSimples\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo referente às possíveis opções de escolha pelo Simples.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:enumeration value=\"0\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Não-optante pelo Simples Federal nem Municipal.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Optante pelo Simples Federal (Alíquota de 1,0%).</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"2\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Optante pelo Simples Federal (Alíquota de 0,5%).</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"3\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Optante pelo Simples Municipal.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"4\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Optante pelo Simples Nacional - DAS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"6\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Optante pelo Simples Nacional - DAMSP.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpPagamentoParceladoAntecipado\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo do indicador de nota fiscal de pagamento parcelado antecipado (realizado antes do fornecimento).</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:enumeration value=\"0\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Não.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Sim.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpPercentualCargaTributaria\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo utilizado para o valor do percentual da carga tributária.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:decimal\">");
        nfe.append("<xs:totalDigits value=\"7\" />");
        nfe.append("<xs:fractionDigits value=\"4\" />");
        nfe.append("<xs:minInclusive value=\"0\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>	");
        nfe.append("<xs:simpleType name=\"tpQuantidade\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo padrão para quantidades.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:long\">");
        nfe.append("<xs:pattern value=\"[0-9]{1,15}\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpRazaoSocial\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo Razão Social.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:minLength value=\"0\" />");
        nfe.append("<xs:maxLength value=\"75\" />");
        nfe.append("<xs:whiteSpace value=\"collapse\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpReferencia\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo de referência da nota.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:enumeration value=\"0\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Nota fiscal referenciada para emissão de nota de multa e juros.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Nota fiscal de pagamento parcelado antecipado.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpSerieRPS\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo série de documento.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:minLength value=\"1\" />");
        nfe.append("<xs:maxLength value=\"5\" />");
        nfe.append("<xs:whiteSpace value=\"collapse\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpStatusNFe\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo referente aos possíveis status de NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:enumeration value=\"N\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Normal.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"C\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Cancelada.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"E\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Extraviada.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpSucesso\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo que indica se o pedido do serviço obteve sucesso.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:boolean\">");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpTempoProcessamento\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo referente ao tempo de processamento do lote.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:long\">");
        nfe.append("<xs:pattern value=\"[0-9]{1,15}\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpTipoLogradouro\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo do endereço (Rua, Av, ...).</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:minLength value=\"0\" />");
        nfe.append("<xs:maxLength value=\"3\" />");
        nfe.append("<xs:whiteSpace value=\"collapse\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpTipoNotaReferenciada\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo de nota fiscal referenciada.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:enumeration value=\"0\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>NFTS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpTipoRPS\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo referente aos possíveis tipos de RPS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:enumeration value=\"RPS\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Recibo Provisório de Serviços.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"RPS-M\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Recibo Provisório de Serviços proveniente de Nota Fiscal Conjugada (Mista).</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("<xs:enumeration value=\"RPS-C\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Cupom.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:enumeration>");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpTributacaoNFe\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo referente aos modos de tributação da NFe.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:minLength value=\"1\" />");
        nfe.append("<xs:maxLength value=\"1\" />");
        nfe.append("<xs:whiteSpace value=\"collapse\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpUF\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo UF.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:string\">");
        nfe.append("<xs:minLength value=\"2\" />");
        nfe.append("<xs:maxLength value=\"2\" />");
        nfe.append("<xs:whiteSpace value=\"collapse\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpValor\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo utilizado para valores com 15 dígitos, sendo 13 de corpo e 2 decimais.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:decimal\">");
        nfe.append("<xs:totalDigits value=\"15\" />");
        nfe.append("<xs:fractionDigits value=\"2\" />");
        nfe.append("<xs:minInclusive value=\"0\" />");
        nfe.append("<xs:pattern value=\"0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\\.[0-9]{0,2})?\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<xs:simpleType name=\"tpVersao\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo Versão do Schema.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:restriction base=\"xs:long\">");
        nfe.append("<xs:pattern value=\"[0-9]{1,3}\" />");
        nfe.append("</xs:restriction>");
        nfe.append("</xs:simpleType>");
        nfe.append("<!-- Tipos Complexos -->");
        nfe.append("<xs:complexType name=\"tpEvento\">");
        nfe.append("<xs:sequence>");
        nfe.append("<xs:element name=\"Codigo\" type=\"tipos:tpCodigoEvento\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Código do evento.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"Descricao\" type=\"tipos:tpDescricaoEvento\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Descrição do enveto.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:choice minOccurs =\"0\" maxOccurs =\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Chave para identificação da origem do evento.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:element name=\"ChaveRPS\" type=\"tipos:tpChaveRPS\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Chave do RPS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ChaveNFe\" type=\"tipos:tpChaveNFe\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Chave da NFe.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("</xs:choice>");
        nfe.append("</xs:sequence>");
        nfe.append("</xs:complexType>");
        nfe.append("<xs:complexType name=\"tpCPFCNPJ\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo que representa um CPF/CNPJ.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:choice>");
        nfe.append("<xs:element name=\"CPF\" type=\"tipos:tpCPF\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"CNPJ\" type=\"tipos:tpCNPJ\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("</xs:choice>");
        nfe.append("</xs:complexType>");
        nfe.append("<xs:complexType name=\"tpCPFCNPJNIF\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo que representa um CPF/CNPJ/NIF.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:choice>");
        nfe.append("<xs:element name=\"CPF\" type=\"tipos:tpCPF\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"CNPJ\" type=\"tipos:tpCNPJ\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"NIF\" type=\"tipos:tpNIF\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"NaoNIF\" type=\"tipos:tpNaoNIF\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("</xs:choice>");
        nfe.append("</xs:complexType>");
        nfe.append("<xs:complexType name=\"tpChaveNFeRPS\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo que representa a chave de uma NFS-e e a Chave do RPS que a mesma substitui.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:sequence>");
        nfe.append("<xs:element name=\"ChaveNFe\" type =\"tipos:tpChaveNFe\" minOccurs =\"1\" maxOccurs=\"1\" >");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Chave da NFS-e gerada.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ChaveRPS\" type =\"tipos:tpChaveRPS\" minOccurs =\"1\" maxOccurs=\"1\" >");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Chave do RPS substituído.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("</xs:sequence>");
        nfe.append("</xs:complexType>");
        nfe.append("<xs:complexType name=\"tpChaveNFe\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Chave de identificação da NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:sequence>");
        nfe.append("<xs:element name=\"InscricaoPrestador\" type=\"tipos:tpInscricaoMunicipal\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Inscrição municipal do prestador de serviços.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"NumeroNFe\" type=\"tipos:tpNumero\"minOccurs =\"1\" maxOccurs =\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Número da NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"CodigoVerificacao\" type=\"tipos:tpCodigoVerificacao\"minOccurs =\"0\" maxOccurs =\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Código de verificação da NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("</xs:sequence>");
        nfe.append("</xs:complexType>");
        nfe.append("<xs:complexType name=\"tpChaveRPS\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo que define a chave identificadora de um RPS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:sequence>");
        nfe.append("<xs:element name=\"InscricaoPrestador\" type=\"tipos:tpInscricaoMunicipal\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Inscrição municipal do prestador de serviços.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"SerieRPS\" type=\"tipos:tpSerieRPS\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Série do RPS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"NumeroRPS\" type=\"tipos:tpNumero\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Número do RPS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("</xs:sequence>");
        nfe.append("</xs:complexType>");
        nfe.append("");
        nfe.append("<xs:complexType name=\"tpEnderecoExterior\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo endereço no exterior.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:sequence>");
        nfe.append("<xs:element name=\"cPais\" type=\"tipos:tpCodigoPaisISO\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Código do país (Tabela de Países ISO)</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"cEndPost\" type=\"tipos:tpCodigoEndPostal\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Código alfanumérico do Endereçamento Postal no exterior do prestador do serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"xCidade\" type=\"tipos:tpNomeCidade\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Nome da cidade no exterior do prestador do serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"xEstProvReg\" type=\"tipos:tpEstadoProvinciaRegiao\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Estado, província ou região da cidade no exterior do prestador do serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("</xs:sequence>");
        nfe.append("</xs:complexType>");
        nfe.append("");
        nfe.append("<xs:complexType name=\"tpEndereco\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo Endereço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:sequence>");
        nfe.append("<xs:element name=\"TipoLogradouro\" type=\"tipos:tpTipoLogradouro\" minOccurs=\"0\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"Logradouro\" type=\"tipos:tpLogradouro\" minOccurs=\"0\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"NumeroEndereco\" type=\"tipos:tpNumeroEndereco\" minOccurs=\"0\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"ComplementoEndereco\" type=\"tipos:tpComplementoEndereco\" minOccurs=\"0\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"Bairro\" type=\"tipos:tpBairro\" minOccurs=\"0\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"Cidade\" type=\"tipos:tpCidade\" minOccurs=\"0\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"UF\" type=\"tipos:tpUF\" minOccurs=\"0\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"CEP\" type=\"tipos:tpCEP\" minOccurs=\"0\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"EnderecoExterior\" type=\"tipos:tpEnderecoExterior\" minOccurs=\"0\" maxOccurs=\"1\" />");
        nfe.append("</xs:sequence>");
        nfe.append("</xs:complexType>");
        nfe.append("<xs:complexType name=\"tpInformacoesLote\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informações do lote processado.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:sequence>");
        nfe.append("<xs:element name=\"NumeroLote\" type=\"tipos:tpNumero\" minOccurs =\"0\" maxOccurs =\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Número de lote.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"InscricaoPrestador\" type=\"tipos:tpInscricaoMunicipal\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Inscrição municipal do prestador dos RPS contidos no lote.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"CPFCNPJRemetente\" type=\"tipos:tpCPFCNPJ\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>CNPJ do remetente autorizado a transmitir a mensagem XML.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"DataEnvioLote\" type=\"xs:dateTime\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Data/hora de envio do lote.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"QtdNotasProcessadas\" type=\"tipos:tpQuantidade\" minOccurs =\"1\" maxOccurs =\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Quantidade de RPS do lote.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"TempoProcessamento\" type=\"tipos:tpTempoProcessamento\" minOccurs =\"1\" maxOccurs =\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tempo de processamento do lote.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorTotalServicos\" type=\"tipos:tpValor\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor total dos serviços dos RPS contidos na mensagem XML.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorTotalDeducoes\" type=\"tipos:tpValor\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor total das deduções dos RPS contidos na mensagem XML.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("</xs:sequence>");
        nfe.append("</xs:complexType>");
        nfe.append("<xs:complexType name=\"tpInformacoesPessoa\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo de informações de pessoa.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:sequence>");
        nfe.append("<xs:choice>");
        nfe.append("<xs:element name=\"CPF\" type=\"tipos:tpCPF\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"CNPJ\" type=\"tipos:tpCNPJ\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"NIF\" type=\"tipos:tpNIF\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"NaoNIF\" type=\"tipos:tpNaoNIF\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("</xs:choice>");
        nfe.append("<xs:element name=\"xNome\" type=\"tipos:tpRazaoSocial\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Nome.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"end\" type=\"tipos:tpEndereco\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Endereço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"email\" type=\"tipos:tpEmail\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Endereço eletrônico.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("</xs:sequence>");
        nfe.append("</xs:complexType>");
        nfe.append("<xs:complexType name=\"tpServico\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo com as informações do serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:sequence>");
        nfe.append("<xs:element name=\"modoPrestServ\" type=\"tipos:tpModoPrestacaoServico\" minOccurs=\"1\" maxOccurs=\"1\"></xs:element>");
        nfe.append("<xs:choice>");
        nfe.append("<xs:element name=\"clocalPrestServ\" type=\"tipos:tpCidade\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"cPaisPrestServ\" type=\"tipos:tpCodigoPaisISO\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("</xs:choice>");
        nfe.append("<xs:element name=\"cCIB\" type=\"tipos:tpCCIB\" minOccurs=\"0\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"indCompGov\" type=\"tipos:tpIndicadorCompraGov\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"tpEnteGov\" type=\"tipos:tpEnteGov\" minOccurs=\"0\" maxOccurs=\"1\" />");
        nfe.append("</xs:sequence>");
        nfe.append("</xs:complexType>");
        nfe.append("<xs:complexType name=\"tpIBSCBS\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo das informações do IBS/CBS</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:sequence>");
        nfe.append("<xs:element name=\"dest\" type=\"tipos:tpInformacoesPessoa\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Destinatário.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"adq\" type=\"tipos:tpInformacoesPessoa\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Adquirente.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"serv\" type=\"tipos:tpServico\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informações relativas ao serviço prestado para IBS/CBS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"valores\" type=\"tipos:tpValores\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informações relacionadas aos valores do serviço prestado para IBS e à CBS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("</xs:sequence>");
        nfe.append("</xs:complexType>");
        nfe.append("<xs:complexType name=\"tpNotaReferenciada\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo de informações da nota referenciada.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:sequence>");
        nfe.append("<xs:element name=\"TipoReferencia\" type=\"tipos:tpReferencia\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"TipoNotaReferenciada\" type=\"tipos:tpTipoNotaReferenciada\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"NumeroNFe\" type=\"tipos:tpNumero\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"CodigoVerificacao\" type=\"tipos:tpCodigoVerificacao\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("</xs:sequence>");
        nfe.append("</xs:complexType>");
        nfe.append("<xs:complexType name=\"tpGIBSCBS\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informações relacionadas ao IBS e à CBS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:sequence>");
        nfe.append("<xs:element name=\"cClassTribIBSCBS\" type=\"tipos:tpCClassTribIBSCBS\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("<xs:element name=\"CClassTribReg\" type=\"tipos:tpCClassTribReg\" minOccurs=\"0\" maxOccurs=\"1\" />");
        nfe.append("</xs:sequence>");
        nfe.append("</xs:complexType>");
        nfe.append("<xs:complexType name=\"tpTrib\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informações relacionadas aos tributos IBS e à CBS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:sequence>");
        nfe.append("<xs:element name=\"gIBSCBS\" type=\"tipos:tpGIBSCBS\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("</xs:sequence>");
        nfe.append("</xs:complexType>");
        nfe.append("<xs:complexType name=\"tpValores\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informações relacionadas aos valores do serviço prestado para IBS e à CBS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:sequence>");
        nfe.append("<xs:element name=\"trib\" type=\"tipos:tpTrib\" minOccurs=\"1\" maxOccurs=\"1\" />");
        nfe.append("</xs:sequence>");
        nfe.append("</xs:complexType>");
        nfe.append("<xs:complexType name=\"tpNFe\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo que representa uma NFS-e</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:sequence>");
        nfe.append("<xs:element name=\"Assinatura\" type=\"tipos:tpAssinatura\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Assinatura digital da NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ChaveNFe\" type=\"tipos:tpChaveNFe\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Chave de identificação da NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"DataEmissaoNFe\" type=\"xs:dateTime\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Data de emissão da NFS-e</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"NumeroLote\" type=\"tipos:tpNumero\" minOccurs =\"0\" maxOccurs =\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Número de lote gerador da NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ChaveRPS\" type=\"tipos:tpChaveRPS\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Chave do RPS que originou a NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"TipoRPS\" type=\"tipos:tpTipoRPS\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo do RPS emitido.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"DataEmissaoRPS\" type=\"xs:date\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Data de emissão do RPS que originou a NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"DataFatoGeradorNFe\" type=\"xs:dateTime\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Data do fato gerador da NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"CPFCNPJPrestador\" type=\"tipos:tpCPFCNPJ\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>CPF/CNPJ do Prestador do serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"RazaoSocialPrestador\" type=\"tipos:tpRazaoSocial\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Nome/Razão Social do Prestador.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"EnderecoPrestador\" type=\"tipos:tpEndereco\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Endereço do Prestador.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"EmailPrestador\" type=\"tipos:tpEmail\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>E-mail do Prestador.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"StatusNFe\" type=\"tipos:tpStatusNFe\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Status da NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"DataCancelamento\" type=\"xs:dateTime\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Data de cancelamento da NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"TributacaoNFe\" type=\"tipos:tpTributacaoNFe\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tributação da NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"OpcaoSimples\" type=\"tipos:tpOpcaoSimples\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Opção pelo Simples.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"NumeroGuia\" type=\"tipos:tpNumero\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Número da guia vinculada a NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"DataQuitacaoGuia\" type=\"xs:date\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Data de quitação da guia vinculada a NFS-e.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorServicos\" type=\"tipos:tpValor\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor dos serviços prestados.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorDeducoes\" type=\"tipos:tpValor\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor das deduções.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorPIS\" type=\"tipos:tpValor\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor da retenção do PIS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorCOFINS\" type=\"tipos:tpValor\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor da retenção do COFINS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorINSS\" type=\"tipos:tpValor\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor da retenção do INSS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorIR\" type=\"tipos:tpValor\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor da retenção do IR.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorCSLL\" type=\"tipos:tpValor\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor da retenção do CSLL.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"CodigoServico\" type=\"tipos:tpCodigoServico\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Código do serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"AliquotaServicos\" type=\"tipos:tpAliquota\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor da alíquota.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorISS\" type=\"tipos:tpValor\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor do ISS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorCredito\" type=\"tipos:tpValor\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor do crédito gerado.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ISSRetido\" type=\"xs:boolean\" minOccurs=\"1\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Retenção do ISS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"CPFCNPJTomador\" type=\"tipos:tpCPFCNPJ\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>CPF/CNPJ do tomador do serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"InscricaoMunicipalTomador\" type=\"tipos:tpInscricaoMunicipal\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Inscrição Municipal do Tomador.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"InscricaoEstadualTomador\" type=\"tipos:tpInscricaoEstadual\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Inscrição Estadual do tomador.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"RazaoSocialTomador\" type=\"tipos:tpRazaoSocial\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Nome/Razão Social do tomador.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"EnderecoTomador\" type=\"tipos:tpEndereco\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Endereço do tomador.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"EmailTomador\" type=\"tipos:tpEmail\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>E-mail do tomador.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"CPFCNPJIntermediario\" type=\"tipos:tpCPFCNPJ\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>CNPJ do intermediário de serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"InscricaoMunicipalIntermediario\" type=\"tipos:tpInscricaoMunicipal\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Inscrição Municipal do intermediário de serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ISSRetidoIntermediario\" type=\"xs:string\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Retenção do ISS pelo intermediário de serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"EmailIntermediario\" type=\"tipos:tpEmail\" minOccurs=\"0\" maxOccurs=\"1\">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>E-mail do intermediário de serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"Discriminacao" type=\"tipos:tpDiscriminacao" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Descrição dos serviços.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorCargaTributaria" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor da carga tributária total em R$.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"PercentualCargaTributaria" type=\"tipos:tpPercentualCargaTributaria" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor percentual da carga tributária.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"FonteCargaTributaria" type=\"tipos:tpFonteCargaTributaria" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Fonte de informação da carga tributária.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"CodigoCEI" type=\"tipos:tpNumero" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Código do CEI – Cadastro específico do INSS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"MatriculaObra" type=\"tipos:tpNumero" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Código que representa a matrícula da obra no sistema de cadastro de obras.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"MunicipioPrestacao" type=\"tipos:tpCidade" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Código da cidade do município da prestação do serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"NumeroEncapsulamento" type=\"tipos:tpNumero" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Código que representa o número do encapsulamento da obra.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorTotalRecebido" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor do total recebido.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:choice>");
        nfe.append("<xs:element name=\"ValorInicialCobrado" type=\"tipos:tpValor" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor inicial cobrado pela prestação do serviço, antes de tributos, multa e juros.</xs:documentation>");
        nfe.append("<xs:documentation>“Valor dos serviços antes dos tributos”. Corresponde ao valor cobrado pela prestação do serviço, antes de tributos, multa e juros.</xs:documentation>");
        nfe.append("<xs:documentation>Informado para realizar o cálculo dos tributos do início para o fim.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorFinalCobrado" type=\"tipos:tpValor" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor final cobrado pela prestação do serviço, incluindo todos os tributos.</xs:documentation>");
        nfe.append("<xs:documentation>“Valor total na nota”. Corresponde ao valor final cobrado pela prestação do serviço, incluindo todos os tributos, multa e juros</xs:documentation>");
        nfe.append("<xs:documentation>Informado para realizar o cálculo dos impostos do fim para o início.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("</xs:choice>");
        nfe.append("<xs:element name=\"ValorMulta" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor da multa.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorJuros" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor dos juros.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorDeducaoCIBS" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor de dedução da base de cálculo do IBS e CBS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorIPI" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor de IPI.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ExigibilidadeSuspensa" type=\"tipos:tpExigibilidadeSuspensa" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe se é uma emissão com exigibilidade suspensa.</xs:documentation>");
        nfe.append("<xs:documentation>0 - Não.</xs:documentation>");
        nfe.append("<xs:documentation>1 - Sim.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"Onerosidade" type=\"tipos:tpOnerosidade" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe se o serviço é oneroso.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"PagamentoParceladoAntecipado" type=\"tipos:tpPagamentoParceladoAntecipado" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe se a nota teve pagamento parcelado antecipado.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"NCM" type=\"tipos:tpCodigoNCM" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o número NCM (Nomenclatura Comum do Mercosul).</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"NBS" type=\"tipos:tpCodigoNBS" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o número NBS (Nomenclatura Brasileira de Serviços).</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"NotaReferenciada" type=\"tipos:tpNotaReferenciada" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informações da nota referenciada.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"IBSCBS" type=\"tipos:tpIBSCBS" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informações declaradas pelo emitente referentes ao IBS e à CBS.</xs:documentation>");
        nfe.append("</xs:annotation> ");
        nfe.append("</xs:element>");
        nfe.append("</xs:sequence>");
        nfe.append("</xs:complexType>");
        nfe.append("<xs:complexType name=\"tpRPS">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Tipo que representa um RPS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("<xs:sequence>");
        nfe.append("<xs:element name=\"Assinatura" type=\"tipos:tpAssinatura" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Assinatura digital do RPS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ChaveRPS" type=\"tipos:tpChaveRPS" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe a chave do RPS emitido.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"TipoRPS" type=\"tipos:tpTipoRPS" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o Tipo do RPS emitido.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"DataEmissao" type=\"xs:date" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe a Data de emissão do RPS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"StatusRPS" type=\"tipos:tpStatusNFe" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o Status do RPS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"TributacaoRPS" type=\"tipos:tpTributacaoNFe" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o tipo de tributação do RPS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorServicos" type=\"tipos:tpValor" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o valor dos serviços prestados.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorDeducoes" type=\"tipos:tpValor" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o valor das deduções.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorPIS" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o valor da retenção do PIS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorCOFINS" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o valor da retenção do COFINS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorINSS" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o valor da retenção do INSS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorIR" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o valor da retenção do IR.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorCSLL" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o valor da retenção do CSLL.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"CodigoServico" type=\"tipos:tpCodigoServico" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o código do serviço do RPS. Este código deve pertencer à lista de serviços.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"AliquotaServicos" type=\"tipos:tpAliquota" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o valor da alíquota. Obs. O conteúdo deste campo será ignorado caso a tributação ocorra no município (Situação do RPS = T ).</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ISSRetido" type=\"xs:boolean" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe a retenção.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"CPFCNPJTomador" type=\"tipos:tpCPFCNPJ" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o CPF/CNPJ do tomador do serviço. O conteúdo deste campo será ignorado caso o campo InscricaoMunicipalTomador esteja preenchido.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"InscricaoMunicipalTomador" type=\"tipos:tpInscricaoMunicipal" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe a Inscrição Municipal do Tomador. ATENÇÃO: Este campo só deverá ser preenchido para tomadores estabelecidos no município de São Paulo (CCM). Quando este campo for preenchido, seu conteúdo será considerado como prioritário com relação ao campo de CPF/CNPJ do Tomador, sendo utilizado para identificar o Tomador e recuperar seus dados da base de dados da Prefeitura.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"InscricaoEstadualTomador" type=\"tipos:tpInscricaoEstadual" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe a inscrição estadual do tomador. Este campo será ignorado caso seja fornecido um CPF/CNPJ ou a Inscrição Municipal do tomador pertença ao município de São Paulo.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"RazaoSocialTomador" type=\"tipos:tpRazaoSocial" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o Nome/Razão Social do tomador. Este campo é obrigatório apenas para tomadores Pessoa Jurídica (CNPJ). Este campo será ignorado caso seja fornecido um CPF/CNPJ ou a Inscrição Municipal do tomador pertença ao município de São Paulo.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"EnderecoTomador" type=\"tipos:tpEndereco" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o endereço do tomador. Os campos do endereço são obrigatórios apenas para tomadores pessoa jurídica (CNPJ informado). O conteúdo destes campos será ignorado caso seja fornecido um CPF/CNPJ ou a Inscrição Municipal do tomador pertença ao município de São Paulo.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"EmailTomador" type=\"tipos:tpEmail" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o e-mail do tomador.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"CPFCNPJIntermediario" type=\"tipos:tpCPFCNPJ" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>CNPJ do intermediário de serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"InscricaoMunicipalIntermediario" type=\"tipos:tpInscricaoMunicipal" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Inscrição Municipal do intermediário de serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ISSRetidoIntermediario" type=\"xs:string" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Retenção do ISS pelo intermediário de serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"EmailIntermediario" type=\"tipos:tpEmail" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>E-mail do intermediário de serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"Discriminacao" type=\"tipos:tpDiscriminacao" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe a discriminação dos serviços.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorCargaTributaria" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor da carga tributária total em R$.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"PercentualCargaTributaria" type=\"tipos:tpPercentualCargaTributaria" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor percentual da carga tributária.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"FonteCargaTributaria" type=\"tipos:tpFonteCargaTributaria" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Fonte de informação da carga tributária.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"CodigoCEI" type=\"tipos:tpNumero" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Código do CEI – Cadastro específico do INSS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"MatriculaObra" type=\"tipos:tpNumero" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Código que representa a matrícula da obra no sistema de cadastro de obras.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"MunicipioPrestacao" type=\"tipos:tpCidade" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Código da cidade do município da prestação do serviço.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"NumeroEncapsulamento" type=\"tipos:tpNumero" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Código que representa o número do encapsulamento da obra.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorTotalRecebido" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor do total recebido.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:choice>");
        nfe.append("<xs:element name=\"ValorInicialCobrado" type=\"tipos:tpValor" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor inicial cobrado pela prestação do serviço, antes de tributos, multa e juros.</xs:documentation>");
        nfe.append("<xs:documentation>“Valor dos serviços antes dos tributos”. Corresponde ao valor cobrado pela prestação do serviço, antes de tributos, multa e juros.</xs:documentation>");
        nfe.append("<xs:documentation>Informado para realizar o cálculo dos tributos do início para o fim.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorFinalCobrado" type=\"tipos:tpValor" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor final cobrado pela prestação do serviço, incluindo todos os tributos.</xs:documentation>");
        nfe.append("<xs:documentation>“Valor total na nota”. Corresponde ao valor final cobrado pela prestação do serviço, incluindo todos os tributos, multa e juros</xs:documentation>");
        nfe.append("<xs:documentation>Informado para realizar o cálculo dos impostos do fim para o início.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("</xs:choice>");
        nfe.append("<xs:element name=\"ValorMulta" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor da multa.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorJuros" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor dos juros.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorDeducaoCIBS" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor de dedução da base de cálculo do IBS e CBS.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ValorIPI" type=\"tipos:tpValor" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Valor de IPI</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"ExigibilidadeSuspensa" type=\"tipos:tpExigibilidadeSuspensa" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe se é uma emissão com exigibilidade suspensa.</xs:documentation>");
        nfe.append("<xs:documentation>0 - Não.</xs:documentation>");
        nfe.append("<xs:documentation>1 - Sim.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"Onerosidade" type=\"tipos:tpOnerosidade" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe se o serviço é oneroso.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"PagamentoParceladoAntecipado" type=\"tipos:tpPagamentoParceladoAntecipado" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe se a nota teve pagamento parcelado antecipado.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"NCM" type=\"tipos:tpCodigoNCM" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o número NCM (Nomenclatura Comum do Mercosul).</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"NBS" type=\"tipos:tpCodigoNBS" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informe o número NBS (Nomenclatura Brasileira de Serviços).</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"NotaReferenciada" type=\"tipos:tpNotaReferenciada" minOccurs=\"0" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informações da nota referenciada.</xs:documentation>");
        nfe.append("</xs:annotation>");
        nfe.append("</xs:element>");
        nfe.append("<xs:element name=\"IBSCBS" type=\"tipos:tpIBSCBS" minOccurs=\"1" maxOccurs=\"1">");
        nfe.append("<xs:annotation>");
        nfe.append("<xs:documentation>Informações declaradas pelo emitente referentes ao IBS e à CBS.</xs:documentation>");
        nfe.append("</xs:annotation> ");
        nfe.append("</xs:element>");
        nfe.append("</xs:sequence>");
        nfe.append("</xs:complexType>");
        nfe.append("</xs:schema>");


        return nfe.toString();

    }


}
